### PR TITLE
windows 10 bug fixed

### PR DESCRIPTION
**Pull request by ravindra1307**
__log_into_file function is creating an error
	

It's due to the default behaviour of open in Python 3. By default, Python 3 will open files in Text mode, which means that it also has to apply a text decoding, such as utf-8 or ASCII, for every character it reads.

Python will use your locale to determine the most suitable encoding. On OS X and Linux, this is usually UTF-8. On Windows, it'll use an 8-bit character set, such windows-1252, to match the behaviour of Notepad.

so i added encoding with open. this fixed the error.

Describe your changes or your new module and let us know which OS and Python version you tested on.
_________________
**OS**: `windows`

**OS Version**: `windows 10`

**Python Version**: `3.6`

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
Hello,

Thank you for your contributions, I will get back to you soon.

Regards.

**Comment by Ali-Razmjoo** [comment]
Hello, 

Thank you for your contribution, there are a few bugs in SQLite queries regarding Unicode too, I will fix them soon. PR merged.

Best Regards.

**Comment by ravindra1307** [comment]
i can help you in that. please guide me what are the bugs ?

**Comment by Ali-Razmjoo** [comment]
Hey,

Hello, it was regarding my last update for database... and just fixed in last commit with `log["DESCRIPTION"].encode('utf8') if version() is 2 else log["DESCRIPTION"]`.

Thanks.

**Pull request merged**
