### PR TITLE
added single ipv6 support

### PR DESCRIPTION
**Pull request by ravindra1307**
added support of single IPv6 in all the scans
currently working on expanding range ipv6 and CIDR ipv6

_________________
**OS**: `windows`

**OS Version**: `windows 10`

**Python Version**: `3.6`

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
Hello,

Thank you for your contribution, I'll check and test your codes tomorrow. please keep in mind to update `--range`/`-r` switch. it's getting the range of IP addresses from online whois database. (#18)

Regards.

**Comment by ravindra1307** [comment]
I will update that soon. And i will soon expand the working with ipv6 range target types also

**Comment by Ali-Razmjoo** [comment]
Hello,

PR merged! looking forward to getting more contribution from you.

Best Regards.

**Comment by ravindra1307** [comment]
thanks i am enjoying on working with this project and i will keep on contributing

**Pull request merged**
