### PR TITLE
Fixes issue #69

### PR DESCRIPTION
**Pull request by shaddygarg**
This PR fixes issue #69
screenshot from 2018-03-11 19-14-24

 
_________________
**OS**: `Ubuntu`

**OS Version**: `17.10`

**Python Version**: `2.7`

### CODE REVIEW

**Comment by pradeepjairamani** [comment]
Hello,

Does it work like this?
using :80:80:80:80
I am having trouble understanding this

Best Regards
Pradeep Jairamani

**Comment by shaddygarg** [comment]
Hey @pradeepjairamani, 
I have fixed the issue in the latest commit.
Regards

**Comment by shaddygarg** [comment]
This also closes #67

**Comment by Ali-Razmjoo** [comment]
Hello,

Thank you for your contribution. PR merged.

Best Regards.

**Pull request merged**
