### PR TITLE
added filelock support to avoid collision while writing logs

### PR DESCRIPTION
**Pull request by avhvr**
Regarding #22 

Created ` __log_into_file(filename, mode, data)` in [core/log.py](https://github.com/avhvr/OWASP-Nettacker/blob/master/core/log.py#L88) 
used [filelock](https://filelock.readthedocs.io/en/latest/) module (works on windows too)

changed blocks of code in following files: 

- lib/brute/smtp/engine.py
- lib/brute/ssh/engine.py
- lib/brute/ftp/engine.py
- lib/vuln/heartbleed/engine.py
- lib/scan/dir/engine.py
- lib/scan/viewdns_reverse_ip_lookup/engine.py
- lib/scan/tcp_connect_port/engine.py
- lib/scan/subdomain/engine.py

Feedback is appreciated
_________________
**OS**: `KDE neon LTS`

**OS Version**: `5.8`

**Python Version**: `3.5.2`

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
Hello,

Thank you for your contribution. I'll check up your code and back to you shortly.

Best Regards.

**Comment by Ali-Razmjoo** [comment]
Hello,


I've tested it on Python 2 and 3, both have the same error. But I've looked into the Travis-CI it has not!
```
python3 nettacker.py -i 127.0.0.1 -m viewdns_reverse_ip_lookup_scan

   ______          __      _____ _____
  / __ \ \        / /\    / ____|  __ \
 | |  | \ \  /\  / /  \  | (___ | |__) |
 | |  | |\ \/  \/ / /\ \  \___ \|  ___/
 | |__| | \  /\  / ____ \ ____) | |     Version 0.0.1
  \____/   \/  \/_/    \_\_____/|_|     SAME
                          _   _      _   _             _
                         | \ | |    | | | |           | |
  github.com/viraintel   |  \| | ___| |_| |_ __ _  ___| | _____ _ __
  owasp.org              | . ` |/ _ \ __| __/ _` |/ __| |/ / _ \ '__|
  viraintel.com          | |\  |  __/ |_| || (_| | (__|   <  __/ |
                         |_| \_|\___|\__|\__\__,_|\___|_|\_\___|_|



[+] Nettacker engine started ...


[+] You are using the last version of OWASP Nettacker ...
[+] 11 modules loaded ...
[+] target 127.0.0.1 submitted!
Process 127.0.0.1->viewdns_reverse_ip_lookup_scan:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/Users/Zombie/Downloads/Compressed/OWASP-Nettacker-master/core/attack.py", line 20, in start_attack
    verbose_level, socks_proxy, retries, ping_flag, methods_args, scan_id, scan_cmd)
  File "/mnt/c/Users/Zombie/Downloads/Compressed/OWASP-Nettacker-master/lib/scan/viewdns_reverse_ip_lookup/engine.py", line 103, in start
    __log_into_file(log_in_file, 'a', data)
  File "/mnt/c/Users/Zombie/Downloads/Compressed/OWASP-Nettacker-master/core/log.py", line 94, in __log_into_file
    flock.acquire()
UnboundLocalError: local variable 'flock' referenced before assignment
[+] start attacking 127.0.0.1, 1 of 1
[+] trying 1 of 1 in process 1 of 1 on 127.0.0.1 (viewdns ip lookup)
[+] domain found: 0-0fx.net
[+] domain found: 0000003.com
[+] removing temp files!
[+] sorting results!
[+] building graph ...
[+] finish building graph!

[+] done!



python nettacker.py -i 127.0.0.1 -m viewdns_reverse_ip_lookup_scan



   ______          __      _____ _____
  / __ \ \        / /\    / ____|  __ \
 | |  | \ \  /\  / /  \  | (___ | |__) |
 | |  | |\ \/  \/ / /\ \  \___ \|  ___/
 | |__| | \  /\  / ____ \ ____) | |     Version 0.0.1
  \____/   \/  \/_/    \_\_____/|_|     SAME
                          _   _      _   _             _
                         | \ | |    | | | |           | |
  github.com/viraintel   |  \| | ___| |_| |_ __ _  ___| | _____ _ __
  owasp.org              | . ` |/ _ \ __| __/ _` |/ __| |/ / _ \ '__|
  viraintel.com          | |\  |  __/ |_| || (_| | (__|   <  __/ |
                         |_| \_|\___|\__|\__\__,_|\___|_|\_\___|_|



[+] Nettacker engine started ...


[+] You are using the last version of OWASP Nettacker ...
[+] 11 modules loaded ...
[+] target 127.0.0.1 submitted!
[+] start attacking 127.0.0.1, 1 of 1
[+] trying 1 of 1 in process 1 of 1 on 127.0.0.1 (viewdns ip lookup)
[+] domain found: 0-0fx.net
[+] domain found: 0000003.com
Process 127.0.0.1->viewdns_reverse_ip_lookup_scan:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Zombie\Downloads\Compressed\OWASP-Nettacker-master\core\attack.py", line 20, in start_attack
    verbose_level, socks_proxy, retries, ping_flag, methods_args, scan_id, scan_cmd)
  File "C:\Users\Zombie\Downloads\Compressed\OWASP-Nettacker-master\lib\scan\viewdns_reverse_ip_lookup\engine.py", line 103, in start
    __log_into_file(log_in_file, 'a', data)
  File "C:\Users\Zombie\Downloads\Compressed\OWASP-Nettacker-master\core\log.py", line 94, in __log_into_file
    flock.acquire()
UnboundLocalError: local variable 'flock' referenced before assignment
[+] removing temp files!
[+] sorting results!
[+] building graph ...
[+] finish building graph!

[+] done!



```

Please check and let me if you can find any details.
Regards.

**Comment by avhvr** [comment]
Ok

**Comment by Ali-Razmjoo** [comment]
Hello,

it has the same problem.

```
   ______          __      _____ _____
  / __ \ \        / /\    / ____|  __ \
 | |  | \ \  /\  / /  \  | (___ | |__) |
 | |  | |\ \/  \/ / /\ \  \___ \|  ___/
 | |__| | \  /\  / ____ \ ____) | |     Version 0.0.1
  \____/   \/  \/_/    \_\_____/|_|     SAME
                          _   _      _   _             _
                         | \ | |    | | | |           | |
  github.com/viraintel   |  \| | ___| |_| |_ __ _  ___| | _____ _ __
  owasp.org              | . ` |/ _ \ __| __/ _` |/ __| |/ / _ \ '__|
  viraintel.com          | |\  |  __/ |_| || (_| | (__|   <  __/ |
                         |_| \_|\___|\__|\__\__,_|\___|_|\_\___|_|



[+] Nettacker engine started ...


[+] You are using the last version of OWASP Nettacker ...
[+] 11 modules loaded ...
[+] target 127.0.0.1 submitted!
[+] start attacking 127.0.0.1, 1 of 1
[+] trying 1 of 1 in process 1 of 1 on 127.0.0.1 (viewdns ip lookup)
[+] domain found: 0-0fx.net
[+] domain found: 0000003.com
Process 127.0.0.1->viewdns_reverse_ip_lookup_scan:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Zombie\Documents\GitHub\test\OWASP-Nettacker\core\attack.py", line 20, in start_attack
    verbose_level, socks_proxy, retries, ping_flag, methods_args, scan_id, scan_cmd)
  File "C:\Users\Zombie\Documents\GitHub\test\OWASP-Nettacker\lib\scan\viewdns_reverse_ip_lookup\engine.py", line 103, in start
    __log_into_file(log_in_file, 'a', data)
  File "C:\Users\Zombie\Documents\GitHub\test\OWASP-Nettacker\core\log.py", line 94, in __log_into_file
    flock.acquire()
UnboundLocalError: local variable 'flock' referenced before assignment
[+] removing temp files!
[+] sorting results!
[+] building graph ...
[+] finish building graph!

[+] done!

```

I believe the new function is working wrong. I've two questions regarding this.
* why you are using `write_blocks` array and appending the file name in it without using it anywhere else?
* should `flock = lockfile.FileLock(filename)` be inside the `if` ? i've tested it outside the if, framework is working fine!
```
def __log_into_file(filename, mode, data):

    if filename not in write_blocks:
        write_blocks.append(filename)
        flock = lockfile.FileLock(filename)

    flock.acquire()
    with open(filename, mode) as save:
        save.write(data + '\n')
    flock.release()
```

Regards.

**Comment by avhvr** [comment]
updated the core/log.py
Can you check again @Ali-Razmjoo

**Comment by Ali-Razmjoo** [comment]
Hello,

Thank you for your contribution, It's fixed now, I hope we see more contribution from you.

PR Merged.
Best Regards.

**Comment by avhvr** [comment]
Thank you. 

Will contribute further.

**Comment by Ali-Razmjoo** [comment]
Hello Again,

Just leaving a message to #1 

Regards.

**Pull request merged**
